sudo: required
services:
        - docker

before_insall:
        - docker build -t suh0025/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true suh0025/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker"
        env: "Docker-env"
        bucket_name: "elasticbeanstalk-us-east-2-838930016859"
        bucket_path: "docker"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "AWS_SECRET_KEY"
